server:
  port: 8777
  servlet: 
    jsp: 
       init-parameters: 
         development: true
spring:
  application:
    name: peesystem
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    name: course
    url: jdbc:mysql://localhost:3306/logsystem?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 990623
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


    
logging:
  config: classpath:logback-spring.xml

mybatis:
  type-aliases-package: com.peesystem.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
    #mappers 多个接口时逗号隔开
    mappers: com.peesystem.common.base.MyBaseMapper
    not-empty: false

    

pagehelper:
  helperDialect: mysql
  reasonable: true
  rowBoundsWithCount: true
  supportMethodsArguments: true
  offsetAsPageNum: true
  params: pageNum=pageNum;pageSize=pageSize
  
  
spring.mvc.view.prefix: /WEB-INF/page/
spring.mvc.view.suffix: .jsp
